apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rkllm-code-pvc
  namespace: npu-server
spec:
  accessModes: [ReadWriteMany]
  storageClassName: cephfs
  resources:
    requests:
      storage: 15Gi

